### PR TITLE
Updated to Framework7 v1.3.5

### PR DESCRIPTION
**Pull request by niravanu**
Updated to Framework7 v1.3.5

### CODE REVIEW

**Comment by notakaos** [comment]
@niravanu Thank you for your Pull Request!
Could you restore the package name and git URL in package.js?
If you change it, I'll merge the Pull Request.

**Comment by niravanu** [comment]
Done!

**Comment by notakaos** [comment]
@niravanu Thanks!

**Comment by niravanu** [comment]
FYI: https://atmospherejs.com/nobutakaoshiro/framework7-ios-material is still pointing to old version

**Comment by notakaos** [comment]
It has been updated :-)

**Comment by niravanu** [comment]
Great! Thanks! I am closing related issue #4

**Pull request merged**
